### TEST SERVER
GET http://localhost:5050/


###
### REGISTER USER
POST http://localhost:5050/api/register
Content-Type: application/json

{
  "name": "Fadil",
  "email": "fadil@test.com",
  "password": "123456"
}



###
### LOGIN
POST http://localhost:5050/auth/login
Content-Type: application/json

{
  "email": "fadil@test.com",
  "password": "123456"
}

